### ISSUE TITLE
Add option to print full data

### ISSUE THREAD

**Issue by tdegeus** [European-XFEL/h5glance#34]
It would be great to have an option to print the full data, and not only sample data. Sometimes I have relatively small lists (order 1000 entries) which I want to view quickly without writing a Python script using h5py.

**Comment by takluyver** [comment]
It's perhaps not the most obvious, but `-s :` will show you all the data. You can use any Python slicing expression like `-s :100` to select what you want to see.

**Comment by tdegeus** [comment]
I see, thanks! Indeed I did not pick-up on that
