### ISSUE TITLE
Should display each object only once by default

### ISSUE THREAD

**Issue by aparamon** [European-XFEL/h5glance#4]
HDF5 objects (groups and datasets) may be linked from multiple locations, similar to file system hard links. When displaying a file with multiple hard links to an object, it is proposed that such object is displayed in detail only the first time.

When a group is encountered for a second and consecutive times, it is proposed that it is not further expanded. To indicate the multiple-link case, ellipsis `...` symbol may be used, possibly along with a reference to the first-encountered link (something like: ` = /first/encountered/link`).

It might be wise to implement an option to disable the smart behavior.

**Comment by takluyver** [comment]
For files on the filesystem, I would check for hardlinks with the device & inode number. What's the equivalent for objects in an HDF5 file? Is it the 'Location' I see with `h5ls -v` ?
