### ISSUE TITLE
Can't see certain attributes in a scanpy generated h5ad file

### ISSUE THREAD

**Issue by bioinfbloke** [European-XFEL/h5glance#40]
I am running h5glance to inspect an anndata object (see https://scanpy.readthedocs.io/en/stable/tutorials/index.html).

I noticed that it doesn't seem to show any detail for pandas index objects (e.g. for var_names). Could h5glance be adapted to show that?

![image](https://github.com/European-XFEL/h5glance/assets/10518908/bb93f321-c736-430c-b646-5d682d91aea7)

**Comment by takluyver** [comment]
I'm not really familiar with scanpy or anndata, can you give a bit more detail on what you're looking at?

Attributes can be shown in the tree view with `--attrs`.

**Comment by bioinfbloke** [comment]
Sorry I should have RTFM that is what I was looking for!
